# apiVersion: build.openshift.io/v1
# kind: BuildConfig
# metadata:
#   name: bni-auth-build
# spec:
#   source:
#     type: Git
#     git:
#       uri: https://github.com/RizkiRahmann/java-bni-project
#   strategy:
#     type: Source
#     sourceStrategy:
#       from:
#         kind: ImageStreamTag
#         name: openjdk-21:latest
#   output:
#     to:
#       kind: ImageStreamTag
#       name: bni-auth-app:latest
